name: Python CI & Streamlit Health Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=88

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -v

  healthcheck:
    name: Streamlit Health Check
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Streamlit app in background
        run: |
          nohup streamlit run app.py --server.headless true --server.port 8501 &

      - name: Wait for Streamlit to spin up
        run: sleep 10

      - name: Health check
        run: |
          curl --fail http://localhost:8501/ || (echo "Health check failed" && exit 1)
